apiVersion: apps/v1
kind: Deployment
metadata:
  name: JenkinsDeployment
  namespace: dev
  labels:
    app: ecr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecr
  template:
    metadata:
      labels:
        app: ecr
    spec:
      containers:
      - name: ecr
        image: 339712867708.dkr.ecr.eu-west-2.amazonaws.com/galaxypro
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ecr-srv
  namespace: dev   
spec:
  type: ClusterIP
  selector:
    app: ecr           
  ports:
    - protocol: TCP
      port: 8080                     
      targetPort: 80
---      
